export const symptoms: Symptom[] = [
  { id: '1', name: 'Abdominal Pain', category: 'Musculoskeletal' },
  { id: '2', name: 'Abnormal Menstruation', category: 'General' },
  { id: '3', name: 'Acidity', category: 'General' },
  { id: '4', name: 'Acute Liver Failure', category: 'General' },
  { id: '5', name: 'Altered Sensorium', category: 'Neurological' },
  { id: '6', name: 'Anxiety', category: 'General' },
  { id: '7', name: 'Back Pain', category: 'Musculoskeletal' },
  { id: '8', name: 'Belly Pain', category: 'Musculoskeletal' },
  { id: '9', name: 'Blackheads', category: 'Neurological' },
  { id: '10', name: 'Bladder Discomfort', category: 'General' },
  { id: '11', name: 'Blister', category: 'General' },
  { id: '12', name: 'Blood In Sputum', category: 'General' },
  { id: '13', name: 'Bloody Stool', category: 'General' },
  { id: '14', name: 'Blurred And Distorted Vision', category: 'General' },
  { id: '15', name: 'Breathlessness', category: 'Respiratory' },
  { id: '16', name: 'Brittle Nails', category: 'General' },
  { id: '17', name: 'Bruising', category: 'General' },
  { id: '18', name: 'Burning Micturition', category: 'General' },
  { id: '19', name: 'Chest Pain', category: 'Musculoskeletal' },
  { id: '20', name: 'Chills', category: 'General' },
  { id: '21', name: 'Cold Hands And Feets', category: 'General' },
  { id: '22', name: 'Coma', category: 'General' },
  { id: '23', name: 'Congestion', category: 'General' },
  { id: '24', name: 'Constipation', category: 'General' },
  { id: '25', name: 'Continuous Feel Of Urine', category: 'General' },
  { id: '26', name: 'Continuous Sneezing', category: 'General' },
  { id: '27', name: 'Cough', category: 'Respiratory' },
  { id: '28', name: 'Cramps', category: 'General' },
  { id: '29', name: 'Dark Urine', category: 'General' },
  { id: '30', name: 'Dehydration', category: 'General' },
  { id: '31', name: 'Depression', category: 'General' },
  { id: '32', name: 'Diarrhoea', category: 'General' },
  { id: '33', name: 'Dischromic  Patches', category: 'General' },
  { id: '34', name: 'Distention Of Abdomen', category: 'Digestive' },
  { id: '35', name: 'Dizziness', category: 'Neurological' },
  { id: '36', name: 'Drying And Tingling Lips', category: 'General' },
  { id: '37', name: 'Enlarged Thyroid', category: 'General' },
  { id: '38', name: 'Excessive Hunger', category: 'General' },
  { id: '39', name: 'Extra Marital Contacts', category: 'General' },
  { id: '40', name: 'Family History', category: 'General' },
  { id: '41', name: 'Fast Heart Rate', category: 'General' },
  { id: '42', name: 'Fatigue', category: 'General' },
  { id: '43', name: 'Fluid Overload', category: 'General' },
  { id: '44', name: 'Foul Smell Of Urine', category: 'General' },
  { id: '45', name: 'Headache', category: 'Musculoskeletal' },
  { id: '46', name: 'High Fever', category: 'General' },
  { id: '47', name: 'Hip Joint Pain', category: 'Musculoskeletal' },
  { id: '48', name: 'History Of Alcohol Consumption', category: 'General' },
  { id: '49', name: 'Increased Appetite', category: 'General' },
  { id: '50', name: 'Indigestion', category: 'General' },
  { id: '51', name: 'Inflammatory Nails', category: 'General' },
  { id: '52', name: 'Internal Itching', category: 'General' },
  { id: '53', name: 'Irregular Sugar Level', category: 'General' },
  { id: '54', name: 'Irritability', category: 'General' },
  { id: '55', name: 'Irritation In Anus', category: 'General' },
  { id: '56', name: 'Itching', category: 'General' },
  { id: '57', name: 'Joint Pain', category: 'Musculoskeletal' },
  { id: '58', name: 'Knee Pain', category: 'Musculoskeletal' },
  { id: '59', name: 'Lack Of Concentration', category: 'General' },
  { id: '60', name: 'Lethargy', category: 'General' },
  { id: '61', name: 'Loss Of Appetite', category: 'General' },
  { id: '62', name: 'Loss Of Balance', category: 'General' },
  { id: '63', name: 'Loss Of Smell', category: 'General' },
  { id: '64', name: 'Malaise', category: 'General' },
  { id: '65', name: 'Mild Fever', category: 'General' },
  { id: '66', name: 'Mood Swings', category: 'General' },
  { id: '67', name: 'Movement Stiffness', category: 'General' },
  { id: '68', name: 'Mucoid Sputum', category: 'General' },
  { id: '69', name: 'Muscle Pain', category: 'Musculoskeletal' },
  { id: '70', name: 'Muscle Wasting', category: 'General' },
  { id: '71', name: 'Muscle Weakness', category: 'General' },
  { id: '72', name: 'Nausea', category: 'Digestive' },
  { id: '73', name: 'Neck Pain', category: 'Musculoskeletal' },
  { id: '74', name: 'Nodal Skin Eruptions', category: 'Dermatological' },
  { id: '75', name: 'Obesity', category: 'General' },
  { id: '76', name: 'Pain Behind The Eyes', category: 'Musculoskeletal' },
  { id: '77', name: 'Pain During Bowel Movements', category: 'Musculoskeletal' },
  { id: '78', name: 'Pain In Anal Region', category: 'Musculoskeletal' },
  { id: '79', name: 'Painful Walking', category: 'Musculoskeletal' },
  { id: '80', name: 'Palpitations', category: 'General' },
  { id: '81', name: 'Passage Of Gases', category: 'General' },
  { id: '82', name: 'Patches In Throat', category: 'General' },
  { id: '83', name: 'Phlegm', category: 'General' },
  { id: '84', name: 'Polyuria', category: 'General' },
  { id: '85', name: 'Prominent Veins On Calf', category: 'General' },
  { id: '86', name: 'Puffy Face And Eyes', category: 'General' },
  { id: '87', name: 'Pus Filled Pimples', category: 'General' },
  { id: '88', name: 'Receiving Blood Transfusion', category: 'General' },
  { id: '89', name: 'Receiving Unsterile Injections', category: 'General' },
  { id: '90', name: 'Red Sore Around Nose', category: 'General' },
  { id: '91', name: 'Red Spots Over Body', category: 'General' },
  { id: '92', name: 'Redness Of Eyes', category: 'General' },
  { id: '93', name: 'Restlessness', category: 'General' },
  { id: '94', name: 'Runny Nose', category: 'General' },
  { id: '95', name: 'Rusty Sputum', category: 'General' },
  { id: '96', name: 'Scurring', category: 'General' },
  { id: '97', name: 'Shivering', category: 'General' },
  { id: '98', name: 'Silver Like Dusting', category: 'General' },
  { id: '99', name: 'Sinus Pressure', category: 'General' },
  { id: '100', name: 'Skin Peeling', category: 'Dermatological' },
  { id: '101', name: 'Skin Rash', category: 'Dermatological' },
  { id: '102', name: 'Slurred Speech', category: 'General' },
  { id: '103', name: 'Small Dents In Nails', category: 'General' },
  { id: '104', name: 'Spinning Movements', category: 'General' },
  { id: '105', name: 'Spotting  Urination', category: 'General' },
  { id: '106', name: 'Stiff Neck', category: 'General' },
  { id: '107', name: 'Stomach Bleeding', category: 'Digestive' },
  { id: '108', name: 'Stomach Pain', category: 'Musculoskeletal' },
  { id: '109', name: 'Sunken Eyes', category: 'General' },
  { id: '110', name: 'Sweating', category: 'General' },
  { id: '111', name: 'Swelled Lymph Nodes', category: 'General' },
  { id: '112', name: 'Swelling Joints', category: 'General' },
  { id: '113', name: 'Swelling Of Stomach', category: 'Digestive' },
  { id: '114', name: 'Swollen Blood Vessels', category: 'General' },
  { id: '115', name: 'Swollen Extremeties', category: 'General' },
  { id: '116', name: 'Swollen Legs', category: 'General' },
  { id: '117', name: 'Throat Irritation', category: 'General' },
  { id: '118', name: 'Toxic Look (Typhos)', category: 'General' },
  { id: '119', name: 'Ulcers On Tongue', category: 'General' },
  { id: '120', name: 'Unsteadiness', category: 'General' },
  { id: '121', name: 'Visual Disturbances', category: 'General' },
  { id: '122', name: 'Vomiting', category: 'Digestive' },
  { id: '123', name: 'Watering From Eyes', category: 'General' },
  { id: '124', name: 'Weakness In Limbs', category: 'General' },
  { id: '125', name: 'Weakness Of One Body Side', category: 'General' },
  { id: '126', name: 'Weight Gain', category: 'General' },
  { id: '127', name: 'Weight Loss', category: 'General' },
  { id: '128', name: 'Yellow Crust Ooze', category: 'General' },
  { id: '129', name: 'Yellow Urine', category: 'General' },
  { id: '130', name: 'Yellowing Of Eyes', category: 'General' },
  { id: '131', name: 'Yellowish Skin', category: 'Dermatological' },
  { id: '132', name: 'Scurrying', category: 'General' },
  { id: '133', name: 'Tiredness', category: 'General' },
  { id: '134', name: 'Loss Of Taste', category: 'General' },
  { id: '135', name: 'Spotting Urination', category: 'General' },
  { id: '136', name: 'Dyschromic Patches', category: 'General' },
  { id: '137', name: 'Cold Hands And Feet', category: 'General' },
  { id: '138', name: 'Swollen Extremities', category: 'General' },
  { id: '139', name: 'Toxic Look (Typhus)', category: 'General' },
];