export const symptoms: Symptom[] = [
  { id: '1', name: 'Abdominal Pain', category: 'Musculoskeletal', value: 'abdominal_pain' },
  { id: '2', name: 'Abnormal Menstruation', category: 'General', value: 'abnormal_menstruation' },
  { id: '3', name: 'Acidity', category: 'General', value: 'acidity' },
  { id: '4', name: 'Acute Liver Failure', category: 'General', value: 'acute_liver_failure' },
  { id: '5', name: 'Altered Sensorium', category: 'Neurological', value: 'altered_sensorium' },
  { id: '6', name: 'Anxiety', category: 'General', value: 'anxiety' },
  { id: '7', name: 'Back Pain', category: 'Musculoskeletal', value: 'back_pain' },
  { id: '8', name: 'Belly Pain', category: 'Musculoskeletal', value: 'belly_pain' },
  { id: '9', name: 'Blackheads', category: 'Neurological', value: 'blackheads' },
  { id: '10', name: 'Bladder Discomfort', category: 'General', value: 'bladder_discomfort' },
  { id: '11', name: 'Blister', category: 'General', value: 'blister' },
  { id: '12', name: 'Blood In Sputum', category: 'General', value: 'blood_in_sputum' },
  { id: '13', name: 'Bloody Stool', category: 'General', value: 'bloody_stool' },
  { id: '14', name: 'Blurred And Distorted Vision', category: 'General', value: 'blurred_and_distorted_vision' },
  { id: '15', name: 'Breathlessness', category: 'Respiratory', value: 'breathlessness' },
  { id: '16', name: 'Brittle Nails', category: 'General', value: 'brittle_nails' },
  { id: '17', name: 'Bruising', category: 'General', value: 'bruising' },
  { id: '18', name: 'Burning Micturition', category: 'General', value: 'burning_micturition' },
  { id: '19', name: 'Chest Pain', category: 'Musculoskeletal', value: 'chest_pain' },
  { id: '20', name: 'Chills', category: 'General', value: 'chills' },
  { id: '21', name: 'Cold Hands And Feets', category: 'General', value: 'cold_hands_and_feets' },
  { id: '22', name: 'Coma', category: 'General', value: 'coma' },
  { id: '23', name: 'Congestion', category: 'General', value: 'congestion' },
  { id: '24', name: 'Constipation', category: 'General', value: 'constipation' },
  { id: '25', name: 'Continuous Feel Of Urine', category: 'General', value: 'continuous_feel_of_urine' },
  { id: '26', name: 'Continuous Sneezing', category: 'General', value: 'continuous_sneezing' },
  { id: '27', name: 'Cough', category: 'Respiratory', value: 'cough' },
  { id: '28', name: 'Cramps', category: 'General', value: 'cramps' },
  { id: '29', name: 'Dark Urine', category: 'General', value: 'dark_urine' },
  { id: '30', name: 'Dehydration', category: 'General', value: 'dehydration' },
  { id: '31', name: 'Depression', category: 'General', value: 'depression' },
  { id: '32', name: 'Diarrhoea', category: 'General', value: 'diarrhoea' },
  { id: '33', name: 'Dischromic  Patches', category: 'General', value: 'dischromic _patches' },
  { id: '34', name: 'Distention Of Abdomen', category: 'Digestive', value: 'distention_of_abdomen' },
  { id: '35', name: 'Dizziness', category: 'Neurological', value: 'dizziness' },
  { id: '36', name: 'Drying And Tingling Lips', category: 'General', value: 'drying_and_tingling_lips' },
  { id: '37', name: 'Enlarged Thyroid', category: 'General', value: 'enlarged_thyroid' },
  { id: '38', name: 'Excessive Hunger', category: 'General', value: 'excessive_hunger' },
  { id: '39', name: 'Extra Marital Contacts', category: 'General', value: 'extra_marital_contacts' },
  { id: '40', name: 'Family History', category: 'General', value: 'family_history' },
  { id: '41', name: 'Fast Heart Rate', category: 'General', value: 'fast_heart_rate' },
  { id: '42', name: 'Fatigue', category: 'General', value: 'fatigue' },
  { id: '43', name: 'Fluid Overload', category: 'General', value: 'fluid_overload' },
  { id: '44', name: 'Foul Smell Of Urine', category: 'General', value: 'foul_smell_of urine' },
  { id: '45', name: 'Headache', category: 'Musculoskeletal', value: 'headache' },
  { id: '46', name: 'High Fever', category: 'General', value: 'high_fever' },
  { id: '47', name: 'Hip Joint Pain', category: 'Musculoskeletal', value: 'hip_joint_pain' },
  { id: '48', name: 'History Of Alcohol Consumption', category: 'General', value: 'history_of_alcohol_consumption' },
  { id: '49', name: 'Increased Appetite', category: 'General', value: 'increased_appetite' },
  { id: '50', name: 'Indigestion', category: 'General', value: 'indigestion' },
  { id: '51', name: 'Inflammatory Nails', category: 'General', value: 'inflammatory_nails' },
  { id: '52', name: 'Internal Itching', category: 'General', value: 'internal_itching' },
  { id: '53', name: 'Irregular Sugar Level', category: 'General', value: 'irregular_sugar_level' },
  { id: '54', name: 'Irritability', category: 'General', value: 'irritability' },
  { id: '55', name: 'Irritation In Anus', category: 'General', value: 'irritation_in_anus' },
  { id: '56', name: 'Itching', category: 'General', value: 'itching' },
  { id: '57', name: 'Joint Pain', category: 'Musculoskeletal', value: 'joint_pain' },
  { id: '58', name: 'Knee Pain', category: 'Musculoskeletal', value: 'knee_pain' },
  { id: '59', name: 'Lack Of Concentration', category: 'General', value: 'lack_of_concentration' },
  { id: '60', name: 'Lethargy', category: 'General', value: 'lethargy' },
  { id: '61', name: 'Loss Of Appetite', category: 'General', value: 'loss_of_appetite' },
  { id: '62', name: 'Loss Of Balance', category: 'General', value: 'loss_of_balance' },
  { id: '63', name: 'Loss Of Smell', category: 'General', value: 'loss_of_smell' },
  { id: '64', name: 'Malaise', category: 'General', value: 'malaise' },
  { id: '65', name: 'Mild Fever', category: 'General', value: 'mild_fever' },
  { id: '66', name: 'Mood Swings', category: 'General', value: 'mood_swings' },
  { id: '67', name: 'Movement Stiffness', category: 'General', value: 'movement_stiffness' },
  { id: '68', name: 'Mucoid Sputum', category: 'General', value: 'mucoid_sputum' },
  { id: '69', name: 'Muscle Pain', category: 'Musculoskeletal', value: 'muscle_pain' },
  { id: '70', name: 'Muscle Wasting', category: 'General', value: 'muscle_wasting' },
  { id: '71', name: 'Muscle Weakness', category: 'General', value: 'muscle_weakness' },
  { id: '72', name: 'Nausea', category: 'Digestive', value: 'nausea' },
  { id: '73', name: 'Neck Pain', category: 'Musculoskeletal', value: 'neck_pain' },
  { id: '74', name: 'Nodal Skin Eruptions', category: 'Dermatological', value: 'nodal_skin_eruptions' },
  { id: '75', name: 'Obesity', category: 'General', value: 'obesity' },
  { id: '76', name: 'Pain Behind The Eyes', category: 'Musculoskeletal', value: 'pain_behind_the_eyes' },
  { id: '77', name: 'Pain During Bowel Movements', category: 'Musculoskeletal', value: 'pain_during_bowel_movements' },
  { id: '78', name: 'Pain In Anal Region', category: 'Musculoskeletal', value: 'pain_in_anal_region' },
  { id: '79', name: 'Painful Walking', category: 'Musculoskeletal', value: 'painful_walking' },
  { id: '80', name: 'Palpitations', category: 'General', value: 'palpitations' },
  { id: '81', name: 'Passage Of Gases', category: 'General', value: 'passage_of_gases' },
  { id: '82', name: 'Patches In Throat', category: 'General', value: 'patches_in_throat' },
  { id: '83', name: 'Phlegm', category: 'General', value: 'phlegm' },
  { id: '84', name: 'Polyuria', category: 'General', value: 'polyuria' },
  { id: '85', name: 'Prominent Veins On Calf', category: 'General', value: 'prominent_veins_on_calf' },
  { id: '86', name: 'Puffy Face And Eyes', category: 'General', value: 'puffy_face_and_eyes' },
  { id: '87', name: 'Pus Filled Pimples', category: 'General', value: 'pus_filled_pimples' },
  { id: '88', name: 'Receiving Blood Transfusion', category: 'General', value: 'receiving_blood_transfusion' },
  { id: '89', name: 'Receiving Unsterile Injections', category: 'General', value: 'receiving_unsterile_injections' },
  { id: '90', name: 'Red Sore Around Nose', category: 'General', value: 'red_sore_around_nose' },
  { id: '91', name: 'Red Spots Over Body', category: 'General', value: 'red_spots_over_body' },
  { id: '92', name: 'Redness Of Eyes', category: 'General', value: 'redness_of_eyes' },
  { id: '93', name: 'Restlessness', category: 'General', value: 'restlessness' },
  { id: '94', name: 'Runny Nose', category: 'General', value: 'runny_nose' },
  { id: '95', name: 'Rusty Sputum', category: 'General', value: 'rusty_sputum' },
  { id: '96', name: 'Scurring', category: 'General', value: 'scurring' },
  { id: '97', name: 'Shivering', category: 'General', value: 'shivering' },
  { id: '98', name: 'Silver Like Dusting', category: 'General', value: 'silver_like_dusting' },
  { id: '99', name: 'Sinus Pressure', category: 'General', value: 'sinus_pressure' },
  { id: '100', name: 'Skin Peeling', category: 'Dermatological', value: 'skin_peeling' },
  { id: '101', name: 'Skin Rash', category: 'Dermatological', value: 'skin_rash' },
  { id: '102', name: 'Slurred Speech', category: 'General', value: 'slurred_speech' },
  { id: '103', name: 'Small Dents In Nails', category: 'General', value: 'small_dents_in_nails' },
  { id: '104', name: 'Spinning Movements', category: 'General', value: 'spinning_movements' },
  { id: '105', name: 'Spotting  Urination', category: 'General', value: 'spotting_ urination' },
  { id: '106', name: 'Stiff Neck', category: 'General', value: 'stiff_neck' },
  { id: '107', name: 'Stomach Bleeding', category: 'Digestive', value: 'stomach_bleeding' },
  { id: '108', name: 'Stomach Pain', category: 'Musculoskeletal', value: 'stomach_pain' },
  { id: '109', name: 'Sunken Eyes', category: 'General', value: 'sunken_eyes' },
  { id: '110', name: 'Sweating', category: 'General', value: 'sweating' },
  { id: '111', name: 'Swelled Lymph Nodes', category: 'General', value: 'swelled_lymph_nodes' },
  { id: '112', name: 'Swelling Joints', category: 'General', value: 'swelling_joints' },
  { id: '113', name: 'Swelling Of Stomach', category: 'Digestive', value: 'swelling_of_stomach' },
  { id: '114', name: 'Swollen Blood Vessels', category: 'General', value: 'swollen_blood_vessels' },
  { id: '115', name: 'Swollen Extremeties', category: 'General', value: 'swollen_extremeties' },
  { id: '116', name: 'Swollen Legs', category: 'General', value: 'swollen_legs' },
  { id: '117', name: 'Throat Irritation', category: 'General', value: 'throat_irritation' },
  { id: '118', name: 'Toxic Look (Typhos)', category: 'General', value: 'toxic_look_(typhos)' },
  { id: '119', name: 'Ulcers On Tongue', category: 'General', value: 'ulcers_on_tongue' },
  { id: '120', name: 'Unsteadiness', category: 'General', value: 'unsteadiness' },
  { id: '121', name: 'Visual Disturbances', category: 'General', value: 'visual_disturbances' },
  { id: '122', name: 'Vomiting', category: 'Digestive', value: 'vomiting' },
  { id: '123', name: 'Watering From Eyes', category: 'General', value: 'watering_from_eyes' },
  { id: '124', name: 'Weakness In Limbs', category: 'General', value: 'weakness_in_limbs' },
  { id: '125', name: 'Weakness Of One Body Side', category: 'General', value: 'weakness_of_one_body_side' },
  { id: '126', name: 'Weight Gain', category: 'General', value: 'weight_gain' },
  { id: '127', name: 'Weight Loss', category: 'General', value: 'weight_loss' },
  { id: '128', name: 'Yellow Crust Ooze', category: 'General', value: 'yellow_crust_ooze' },
  { id: '129', name: 'Yellow Urine', category: 'General', value: 'yellow_urine' },
  { id: '130', name: 'Yellowing Of Eyes', category: 'General', value: 'yellowing_of_eyes' },
  { id: '131', name: 'Yellowish Skin', category: 'Dermatological', value: 'yellowish_skin' },
  { id: '132', name: 'Scurrying', category: 'General', value: 'scurrying' },
  { id: '133', name: 'Tiredness', category: 'General', value: 'tiredness' },
  { id: '134', name: 'Loss Of Taste', category: 'General', value: 'loss_of_taste' },
  { id: '135', name: 'Spotting Urination', category: 'General', value: 'spotting_urination' },
  { id: '136', name: 'Dyschromic Patches', category: 'General', value: 'dyschromic_patches' },
  { id: '137', name: 'Cold Hands And Feet', category: 'General', value: 'cold_hands_and_feet' },
  { id: '138', name: 'Swollen Extremities', category: 'General', value: 'swollen_extremities' },
  { id: '139', name: 'Toxic Look (Typhus)', category: 'General', value: 'toxic_look_(typhus)' },
];