# Generated by Django 4.2.28 on 2026-02-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
