# Generated by Django 4.2.29 on 2026-04-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(default='General Physician', max_length=100),
        ),
    ]
